### ISSUE TITLE
Advertise the season & kick-off meeting

### ISSUE THREAD

**Issue by Patechoc** [DataForGood-Norway/season-1#1]
* collaborate on the text on a GDoc before next meeting
* design poster
* list channels to share it: universities, engineering schools, hack4no, social media, Tekna, ... 
* contact meetup organizers

**Comment by makingwaves27** [comment]
In terms of creating the Google Doc, is there already a drive for DataForGood, or does one need to be created?  I could of course make one in my own drive but it would be good to have them all in one place.

**Comment by gahjelle** [comment]
- [ ] LinkedIn Account
- [ ] WordCloud
- [ ] Logo
- [ ] QR code
- [ ] Print version
- [ ] SoMe version (FB, LinkedIn)
- [ ] Twitter version
